name: DigCraft
options:
  bundleIdPrefix: com.digcraft
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top

targets:
  DigCraft:
    type: application
    platform: [iOS, macOS]
    sources:
      - DigCraft
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.digcraft.app
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O

  DigCraftTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    sources:
      - DigCraftTests
    dependencies:
      - target: DigCraft_${platform}
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        SWIFT_VERSION: "6.0"
